---
permalink: online-help/concept-all-workloads.html 
sidebar: sidebar 
keywords: workloads,workloads 
summary: 所有工作负载视图显示数据中心集群上所有可用工作负载的列表。 
---
= 所有工作负载
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
所有工作负载视图显示数据中心集群上所有可用工作负载的列表。

所有工作负载视图会列出与 Unified Manager 管理的 ONTAP 集群关联的存储工作负载。此外、您还可以通过此页面为存储工作负载分配存储效率策略和性能服务级别。

将集群添加到 Unified Manager 时，系统会自动发现每个集群上的存储工作负载并将其显示在此页面上，但 FlexGroup 卷及其成分卷除外。

只有在存储工作负载开始执行I/O操作后、Unified Manager才会开始分析工作负载以获得建议(建议的性能服务级别)。对于未执行任何 I/O 操作的新发现的存储工作负载，状态为 "`Waiting for I/O` " 。对存储工作负载执行 I/O 操作后， Unified Manager 将开始分析，工作负载状态将更改为 "`Learning ……` " 。分析完成后(自I/O操作开始起24小时内)、将为存储工作负载显示建议的性能服务级别。

使用 * 工作负载 * > * 所有工作负载 * 选项，您可以执行多项任务：

* 添加或配置存储工作负载
* 查看和筛选工作负载列表
* 为单个存储工作负载分配性能服务级别
* 为所有未分配的工作负载分配系统建议的性能服务级别
* 为存储工作负载分配存储效率策略




== 添加或配置存储工作负载

您可以为支持的 LUN （支持 iSCSI 和 FCP 协议）， NFS 文件共享和 SMB 共享添加或配置存储工作负载。



== 查看和筛选工作负载

在所有工作负载屏幕上、您可以查看数据中心中的所有工作负载、也可以根据分配给这些工作负载的性能服务级别或工作负载名称搜索特定存储工作负载。您可以使用筛选器图标输入搜索的特定条件。您可以按不同的筛选条件进行搜索，例如按主机集群或 Storage VM 进行搜索。如果选择*总容量*选项、则可以按工作负载的总容量进行搜索。返回的工作负载数量可能因输入的确切筛选条件而异、因为容量是在字节级别进行比较的。此屏幕将显示工作负载的存储信息、例如主机集群和Storage VM、以及性能服务级别和存储效率策略(如果有)。

您还可以通过此页面查看工作负载的性能详细信息。您可以通过单击 * 选择 / 排序列 * 按钮并选择要查看的特定列来查看有关工作负载的 IOPS ，容量和延迟的详细信息。" 性能视图 " 列显示工作负载的平均 IOPS 和峰值 IOPS ，您可以单击工作负载分析器图标以查看详细的 IOPS 分析。"IOPS 分析 " 弹出窗口中的 * 分析工作负载 * 按钮将转到 " 工作负载分析 " 页面，在此可以选择一个时间范围并查看选定工作负载的延迟，吞吐量和容量趋势。有关工作负载分析器的详细信息，请参见 _Troubleshooting Workloads Using the Workload analyzer

link:concept-troubleshooting-workloads-using-the-workload-analyzer.adoc["使用工作负载分析器对工作负载进行故障排除"]



== 为存储工作负载分配性能服务级别

您可以为一个或多个存储工作负载分配性能服务级别。通过使用屏幕上的不同导航、您可以为工作负载分配特定或系统建议的性能服务级别。



== 为所有未分配的工作负载分配系统建议的性能服务级别

您可以为数据中心中未分配PSL的所有存储工作负载分配性能服务级别、但前提是这些工作负载具有系统建议的性能服务级别。对于没有任何系统建议的性能服务级别的工作负载、此功能无效。要使用此功能，请单击 * 分配系统建议 PSL* 按钮。系统会在内部评估未分配存储工作负载的适当性能服务级别、并显示可分配性能服务级别的工作负载总数。



== 为存储工作负载分配存储效率策略

您可以将存储效率策略分配给一个或多个存储工作负载。通过使用屏幕上的不同导航、您可以为存储工作负载分配特定的存储效率策略。



== 同时分配性能服务级别和存储效率策略

您可以将性能服务级别和存储效率策略同时分配给单个工作负载。请按照以下步骤操作：

. 单击该行对应的编辑图标、然后单击*编辑*。
+
已启用 * 已分配性能服务级别 * 和 * 存储效率策略 * 字段。

. 选择所需的性能服务级别和存储效率策略。
. 单击复选图标以应用更改。




== 分析工作负载的性能和容量标准

您可以单击 * 性能视图 * 列中的条形图图标来查看有关工作负载的性能信息以帮助进行故障排除。要在 " 工作负载分析 " 页面上查看性能和容量图表以分析对象，请单击 * 分析工作负载 * 按钮。
