---
permalink: online-help/concept-managing-storage-efficiency-policies.html 
sidebar: sidebar 
keywords: add 
summary: '通过存储效率策略(SEP\)、您可以定义工作负载的存储效率特征。您可以在最初创建工作负载时为工作负载分配存储效率策略、也可以稍后通过编辑工作负载来分配存储效率策略。' 
---
= 管理存储效率策略
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
通过存储效率策略（ Storage Efficiency Policy ， SEP ），您可以定义工作负载的存储效率特征。您可以在最初创建工作负载时为工作负载分配存储效率策略、也可以稍后通过编辑工作负载来分配存储效率策略。

存储效率包括使用精简配置，重复数据删除和数据压缩等技术来提高存储利用率并降低存储成本。在创建存储效率策略时、您可以单独使用这些节省空间的技术、也可以同时使用这些技术来实现最大的存储效率。将策略与存储工作负载关联后，系统会为其分配指定的策略设置。通过Unified Manager、您可以分配系统定义的和用户定义的存储效率策略、以优化数据中心中的存储资源。

Unified Manager提供了两个系统定义的存储效率策略：高和低。这些 SEP 适用于数据中心中的大多数存储工作负载，但是，如果系统定义的 SEP 不符合您的要求，您可以创建自己的策略。

您不能修改系统定义的或当前分配给工作负载的存储效率策略。如果分配给工作负载的存储效率策略是唯一可用的存储效率策略、则不能将其删除。

存储效率策略页面列出了可用的存储效率策略、并可用于添加、编辑和删除自定义SEP。此页面显示以下信息：

[cols="1a,1a"]
|===
| 字段 | Description 


 a| 
Name
 a| 
存储效率策略的名称。



 a| 
Type
 a| 
策略是系统定义的还是用户定义的。



 a| 
空间预留
 a| 
卷是精简配置卷还是厚配置卷。



 a| 
重复数据删除
 a| 
卷上是否启用重复数据删除：

* `Inline`：在卷上写入数据时会发生重复数据删除
* `Background`：重复数据删除在后台进行
* `Disable`：卷上已禁用重复数据删除




 a| 
压缩
 a| 
是否在卷上启用数据压缩：

* `Inline`：在卷上写入数据时会进行数据压缩
* `Background`：数据压缩在后台进行
* `Disable`：卷上已禁用数据压缩




 a| 
工作负载
 a| 
已分配存储效率策略的存储工作负载数量

|===


== 创建自定义存储效率策略的准则

如果现有存储效率策略不满足存储工作负载的策略要求、则可以创建自定义存储效率策略。但是、建议您尝试对存储工作负载使用系统定义的存储效率策略、并且仅在必要时才创建自定义存储效率策略。
