---
permalink: online-help/task-configuring-event-notification-settings.html 
sidebar: sidebar 
keywords:  
summary: 您可以将 Unified Manager 配置为在生成事件或将事件分配给用户时发送警报通知。您可以配置用于发送警报的 SMTP 服务器，也可以设置各种通知机制，例如，可以通过电子邮件或 SNMP 陷阱发送警报通知。 
---
= 配置事件通知设置
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以将 Unified Manager 配置为在生成事件或将事件分配给用户时发送警报通知。您可以配置用于发送警报的 SMTP 服务器，也可以设置各种通知机制，例如，警报通知可以通过电子邮件或 SNMP 陷阱发送。



== 开始之前

您必须具有以下信息：

* 发送警报通知的电子邮件地址
+
电子邮件地址将显示在已发送警报通知的 "`from` " 字段中。如果由于任何原因无法传送此电子邮件，则此电子邮件地址也会用作无法传送的邮件的收件人。

* 用于访问服务器的 SMTP 服务器主机名以及用户名和密码
* 要接收 SNMP 陷阱的陷阱目标主机的主机名或 IP 地址，以及 SNMP 版本，出站陷阱端口，社区和其他所需的 SNMP 配置值
+
要指定多个陷阱目标，请使用逗号分隔每个主机。在这种情况下，列表中所有主机的所有其他 SNMP 设置（例如版本和出站陷阱端口）都必须相同。



您必须具有应用程序管理员或存储管理员角色。



== 步骤

. 在左侧导航窗格中，单击 * 常规 * > * 通知 * 。
. 在*通知*页面中、配置相应的设置并单击*保存*。
+
[NOTE]
====
....
**If the From Address is pre-filled with the address "ActiveIQUnifiedManager@localhost.com", you should change it to a real, working email address to make sure that all email notifications are delivered successfully.
** If the host name of the SMTP server cannot be resolved, you can specify the IP address (IPv4 or IPv6) of the SMTP server instead of the host name.
....
====

