---
permalink: online-help/task-provisioning-fileshares.html 
sidebar: sidebar 
keywords:  
summary: '如果有可用空间、您可以通过配置工作负载页面为现有集群和Storage Virtual Machine \(Storage VM\)创建LUN或文件共享\(支持CIFS/SMB和NFS协议\)。' 
---
= 配置工作负载
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果有可用空间、您可以通过配置工作负载页面为现有集群和Storage Virtual Machine (Storage VM)创建LUN (支持iSCSI和FCP协议)或文件共享(支持CIFS/SMB和NFS协议)。



== 开始之前

* 至少应在Storage VM上启用SMB、NFS、iSCSI和FCP服务之一、或者启用所有服务。如果要创建LUN、则必须同时启用iSCSI和FCP。
* 要在工作负载上选择和分配性能服务级别和存储效率策略、必须在开始创建工作负载之前创建这些策略。




== 步骤

. 在*配置工作负载*页面上、添加要创建的工作负载的名称、然后从可用列表中选择要创建工作负载的集群。
. 根据选定的集群、*存储VM*字段将筛选该集群的可用Storage Virtual Machine。从列表中选择所需的 Storage VM 。
+
根据Storage VM上支持的SMB、NFS、iSCSI和FCP服务、已在主机信息部分中启用NAS和SAN选项。

. 在*存储和优化*部分中、为工作负载分配存储容量和性能服务级别以及存储效率策略(可选)。
+
在创建工作负载时、性能服务级别的规范将应用于工作负载、存储效率策略的规范将根据需要分配给卷和LUN。

. 如果要强制实施已分配给工作负载的性能服务级别、请选中*强制实施性能限制*复选框。为工作负载分配性能服务级别可确保创建工作负载的聚合能够支持在相应的性能服务级别中定义的性能和容量目标。例如、如果为工作负载分配了"`Extreme Performance`"、则要配置工作负载的聚合应能够支持"至高性能"性能服务级别的性能和容量目标、例如SSD存储。
+
[NOTE]
====
除非选中此复选框、否则性能服务级别不会应用于工作负载、并且此工作负载在信息板上的状态将显示为未分配。

====
. 如果要创建SMB和/或NFS文件共享、请选择* NAS *按钮。只有在Storage VM启用了所需服务时、才会启用此按钮以供选择。
+
[NOTE]
====
如果SVM同时启用了SMB和NFS服务、则可以选择*通过NFS*共享和*通过SMB*共享按钮并创建一个同时支持NFS和SMB协议的文件共享。如果要创建SMB或CIFS共享、请仅选择相应的按钮。

====
+
.. 对于NFS文件共享、指定用于访问文件共享卷的主机或网络的IP地址。您可以为多个主机输入逗号分隔值。
+
添加主机IP地址时、将运行内部检查、以便将主机详细信息与SVM进行匹配、并为此主机创建导出策略、如果存在现有策略、则会重复使用此策略。如果为同一主机创建了多个 NFS 共享，则会对所有文件共享重复使用具有匹配规则的同一主机的可用导出策略。在使用 API 配置 NFS 共享时，可以通过提供特定策略密钥来指定单个策略的规则或重复使用策略。

.. 对于 SMB 共享，指定可以访问 SMB 共享的用户或用户组并分配所需权限。对于每个用户组，在创建文件共享期间会生成一个新的访问控制列表（ ACL ）。


. 要创建LUN、请选择* SAN *按钮。只有在选定Storage VM启用了所需服务时、才会启用此按钮以供选择。
+
.. 选择主机操作系统。
.. 指定LUN的主机映射。您可以分配现有启动程序组(igroup)、或者定义新的igroup并将其映射到LUN、以控制哪些启动程序可以访问LUN。
+

NOTE: 如果在配置LUN时创建新的igroup、则需要等到下一个发现周期(最长15分钟)才能使用它创建LUN。因此，建议您使用可用 igroup 列表中的现有 igroup 。

+
如果要创建新的igroup、请选择*创建新启动程序组*按钮、然后输入创建此igroup所需的信息。



. 单击 * 保存 * 。


此工作负载将添加到存储工作负载列表中。
