---
permalink: performance-checker/reference-what-data-does-the-workload-analyzer-display.html 
sidebar: sidebar 
keywords: workload analyzer charts 
summary: 工作负载分析器页面显示有关可能影响工作负载的任何当前事件的信息，可能修复导致此事件的问题描述的建议以及用于分析性能和容量历史记录的图表。 
---
= 工作负载分析器显示的数据
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
工作负载分析器页面显示有关可能影响工作负载的任何当前事件的信息，可能修复导致此事件的问题描述的建议以及用于分析性能和容量历史记录的图表。

在页面顶部，您可以指定要分析的工作负载（卷或 LUN ）的名称以及要查看统计信息的时间范围。如果要查看较短或较长的时间段，您可以随时更改时间范围。

此页面的其他区域将显示分析结果以及性能和容量图表。

[NOTE]
====
LUN 的工作负载图表提供的统计信息级别与卷的工作负载图表不同，因此在分析这两种工作负载时，您会发现存在差异。

====
* * 事件摘要区域 *
+
简要概述在此时间范围内发生的事件数量和类型。如果存在来自不同影响区域（例如性能和容量）的事件，则会显示此信息，以便您可以为感兴趣的事件类型选择详细信息。单击事件类型可查看事件名称列表。

+
如果在此时间范围内只有一个事件，则会为某些事件列出修复问题描述的建议列表。

* * 事件时间线 *
+
显示指定时间范围内发生的所有事件。将光标悬停在每个事件上可查看事件名称。

+
如果您通过单击事件详细信息页面中的 * 分析工作负载 * 按钮访问此页面，则选定事件的图标将显示为较大的图标，以便您可以识别该事件。

* * 性能图表区域 *
+
根据您选择的时间范围显示延迟，吞吐量（ IOPS 和 MB/ 秒）和利用率（节点和聚合）图表。您可以单击查看性能详细信息链接以显示工作负载的 " 性能资源管理器 " 页面，以便进行进一步分析。

+
** *延迟*显示工作负载的延迟。此图表包含三个视图、可用于查看总延迟、按读取、写入和其他进程细分的延迟以及按集群组件细分的延迟。
+
请参见 link:concept-cluster-components-and-why-they-can-be-in-contention.html["集群组件及其可能发生争用的原因"] 此处显示的集群组件的问题描述。

** *吞吐量*可显示工作负载的IOPS和MB/秒吞吐量。此图表包含两个视图、可用于查看总吞吐量以及按读取、写入和其他进程细分的吞吐量。
+
此图表还会显示服务质量(QoS)最大和最小吞吐量阈值设置(如果已配置)、以便您可以查看系统可能有意限制吞吐量的位置。

** *利用率*显示运行工作负载的聚合和节点的利用率。您可以从此处查看聚合或节点是否过度利用、从而导致高延迟。分析 FlexGroup 卷时，利用率图表中会列出多个节点和多个聚合。


* * 容量图表区域 *
+
显示工作负载过去一个月的数据容量和 Snapshot 容量图表。

+
对于卷，您可以单击查看容量详细信息链接以显示工作负载的 " 运行状况详细信息 " 页面，以便进行进一步分析。LUN 不提供此链接，因为没有 LUN 的运行状况详细信息页面。

+
** * 容量视图 * 显示为工作负载分配的总可用空间以及已用逻辑空间（经过所有 NetApp 优化后）。
** * 快照视图 * 显示为 Snapshot 副本预留的总空间以及当前正在使用的空间量。请注意， LUN 不提供 Snapshot 视图。这两个图表都包含此工作负载的容量已满前剩余的估计时间。此信息基于历史使用情况，至少需要 10 天的数据。如果剩余容量少于 30 天， Unified Manager 会将存储标识为 "`接近全满` " 。



