---
permalink: install-windows/task-changing-the-jboss-password-on-windows.html 
sidebar: sidebar 
keywords:  
summary: 您可以创建新的自定义JBoss密码以覆盖安装期间设置的默认密码。此任务是可选的、但某些站点可能需要此安全功能来覆盖Unified Manager安装默认设置。此操作还会更改 JBoss 用于访问 MySQL 的密码。 
---
= 更改 JBoss 密码
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以创建新的自定义JBoss密码以覆盖安装期间设置的默认密码。此任务是可选的、但某些站点可能需要此安全功能来覆盖Unified Manager安装默认设置。此操作还会更改 JBoss 用于访问 MySQL 的密码。



== 开始之前

* 对于安装了 Unified Manager 的系统，您必须具有 Windows 管理员权限。
* 您必须具有MySQL root用户的密码。
* 您必须能够访问NetApp提供的 `password.bat` 脚本 `\Program Files\NetApp\essentials\bin`。




== 步骤

. 以管理员用户身份登录到 Unified Manager 主机。
. 使用 Windows 服务控制台停止以下 Unified Manager 服务：
+
** NetApp Active IQ 采集服务（ Ocie-au ）
** NetApp Active IQ 管理服务器服务（ Oncommandsvc ）


. 启动 `password.bat` 用于开始密码更改过程的脚本： `C:\Program Files\NetApp\essentials\bin> password.bat resetJBossPassword`
. 出现提示时，输入 MySQL root 用户密码。
. 出现提示时、输入当前的JBoss用户密码。
+
默认密码为 `D11h1aMu@79%`。

. 出现提示时，输入新的 JBoss 用户密码，然后再次输入以进行确认。
+
在进行更改后、系统将显示确认消息、然后会最后一次提示您输入新的JBoss用户密码。

. 再输入一次新的JBoss用户密码。
. 脚本完成后，使用 Windows 服务控制台启动 Unified Manager 服务：
+
** NetApp Active IQ 管理服务器服务（ Oncommandsvc ）
** NetApp Active IQ 采集服务（ Ocie-au ）


. 启动所有服务后，您可以登录到 Unified Manager UI 。

