---
permalink: install-windows/task-upgrading-to-unified-manager-on-microsoft-windows.html 
sidebar: sidebar 
keywords:  
summary: 您可以通过在Windows平台上下载并运行安装文件将Unified Manager 9.5或9.6升级到9.7。 
---
= 升级 Unified Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以通过在Windows平台上下载并运行安装文件将Unified Manager 9.5或9.6升级到9.7。



== 开始之前

* 要升级 Unified Manager 的系统必须满足系统和软件要求。
+
xref:concept-virtual-infrastructure-or-hardware-system-requirements.adoc[硬件系统要求]

+
xref:reference-windows-software-and-installation-requirements.adoc[Windows 软件和安装要求]

+
[NOTE]
====
从 Unified Manager 9.5 开始， OpenJDK 会随安装包提供并自动安装。从 Unified Manager 9.5 开始，不支持 Oracle Java 。

====
+
[NOTE]
====
从Unified Manager 9.4开始、需要使用Microsoft .NET 4.5.2或更高版本。在开始升级之前、请确保已安装正确版本的.NET。

====
* 您必须具有 Windows 管理员权限。确保您的用户名不以感叹号"`开头!`". Installation of Unified Manager might fail if the user name of user running the installation begins with "`！`"。
* 您必须具有有效凭据才能登录到 NetApp 支持站点。
* 为了避免数据丢失、您必须已为Unified Manager计算机创建备份、以防升级期间存在问题描述。
* 您必须有足够的可用磁盘空间来执行升级。
+
安装驱动器上的可用空间必须大于数据目录大小2.5 GB。升级将停止并显示一条错误消息，指示在可用空间不足时要添加的空间量。

* 在升级期间，系统可能会提示您确认是要保留先前的默认设置以将性能数据保留 13 个月，还是将其更改为 6 个月。确认后，将清除 6 个月后的历史性能数据。
* 升级之前、您必须关闭中所有打开的文件或文件夹 `<InstallDir\>\JDK` 和 `MySQL Data Directory`。




== 关于此任务

在升级过程中， Unified Manager 不可用。在升级 Unified Manager 之前，您应完成所有正在运行的操作。

如果 Unified Manager 与 OnCommand Workflow Automation 实例配对，并且这两种产品都有新版本的软件，则必须断开这两种产品的连接，然后在执行升级后设置新的 Workflow Automation 连接。如果您仅对其中一个产品执行升级，则应在升级后登录到 Workflow Automation ，并验证它是否仍在从 Unified Manager 获取数据。



== 步骤

. 登录到NetApp 支持站点 、找到*下载*页面、以便在Windows平台上安装Unified Manager。
+
https://mysupport.netapp.com/products/index.html[]

. 将Unified Manager Windows安装文件下载到Windows系统中的目标目录。
. 右键单击并运行Unified Manager安装程序可执行文件 `(.exe)` 以管理员身份提交文件。
+
Unified Manager 将提示您显示以下消息：

+
[listing]
----
This setup will perform an upgrade of Unified Manager. Do you want to continue?
----
. 单击 * 是 * ，然后单击 * 下一步 * 。
. 输入在安装期间设置的 MySQL8 根密码，然后单击 * 下一步 * 。
. 登录到 Unified Manager Web UI 并验证版本号。




== 完成后

[NOTE]
====
要对Unified Manager执行静默升级、请运行以下命令： `ActiveIQUnifiedManager-<version\>.exe /s /v"MYSQL_PASSWORD=netapp21! /qn /l*v C:\install.log`

====