---
permalink: install-linux/task-upgrading-mysql-on-linux.html 
sidebar: sidebar 
keywords:  
summary: 您可以在安装了Unified Manager的已连接Linux服务器上升级到较新版本的MySQL、以获取安全漏洞修复。对于任何次要升级、MySQL的基本版本必须为8.0.20或更高版本。如果系统上安装的MySQL版本早于8.0.2、则Unified Manager 9.7升级过程会自动将MySQL升级到8.0.2。您不能将MySQL从早期版本独立升级到8.0.2。 
---
= 在 Linux 上升级 MySQL
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以在安装了Unified Manager的已连接Linux服务器上升级到较新版本的MySQL、以获取安全漏洞修复。对于任何次要升级、MySQL的基本版本必须为8.0.20或更高版本。如果系统上安装的MySQL版本早于8.0.2、则Unified Manager 9.7升级过程会自动将MySQL升级到8.0.2。您不能将MySQL从早期版本独立升级到8.0.2。



== 开始之前

[NOTE]
====
手动升级MySQL仅适用于连接Internet的系统。如果系统上安装的MySQL版本为5.7、则不能尝试直接将MySQL升级到8.0.2版。它会导致应用程序数据丢失。

====
对于安装了 Unified Manager 的 Linux 系统，您必须具有 root 权限。



== 关于此任务

您只能将MySQL 8.0.20的基本版本升级到更高版本、以便进行次要更新。



== 步骤

. 以 root 用户身份登录到 Unified Manager 主机。
. 下载最新的MySQL社区服务器 `.rpm` 捆绑包。
. 将捆绑包解压缩到目标系统上的目录。
. 您可以获得多个 `.rpm` 在取消绑定此软件包后、此目录中的软件包将被取消、但Unified Manager仅需要以下rpm软件包：
+
** mysql-community-client-8.0.20
** mysql-community-libs-8.0.20
** mysql-community-server-8.0.20
** mysql-community-common-8.0.20
** mysql-community-libs-compat-8.0.20


+
删除所有其他 `.rpm` 软件包。但是，将所有软件包安装在 rpm 软件包中不会出现发生原因错误。

. 按所示顺序停止 Unified Manager 服务和关联的 MySQL 软件：
. 使用以下命令调用 MySQL 升级： `yum install *.rpm`
+
`*.rpm` 指 `.rpm` 下载较新版本MySQL的目录中的软件包。

. 按所示顺序启动 Unified Manager ：

